apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-domain-deploy
  labels:
    app: insurance-domain-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurance-domain-app
  template:
    metadata:
      labels:
        app: insurance-domain-app
    spec:
      containers:
      - name: insurance-domain-container
        image: vinisasthi/demo-pro-insurance-domain
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-domain-np-service
  labels:
    app: insurance-domain-app
spec:
  selector:
    app: insurance-domain-app

  type: NodePort
  ports:
  - nodePort: 31038    
    port: 8081
    targetPort: 8081
